### ISSUE TITLE
How do I use this thing?!

### ISSUE THREAD

**Issue by Kai-Bailey** [kenboo98/HackerNews-Terminal#1]

**Comment by aelgohar** [comment]
I think you click the big green download button. Not sure where to go from there though. A README would've helped for sure!

**Comment by kenboo98** [comment]
Thanks for the suggestion guys! 
Below are some steps to get started with HackerNews Terminal:
1. Git clone this repo
2. `cargo run`
3. Start work on the project.

Thanks!
